name: BackstopJS Visual Regression

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL to test'
        required: true
        default: 'https://example.com'
      css_selector:
        description: 'CSS selector to test (optional)'
        required: false
        default: 'document'

jobs:
  backstop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install backstopjs puppeteer

      - name: Generate Backstop Config
        run: |
          echo "TARGET_URL=${{ github.event.inputs.target_url }}" >> $GITHUB_ENV
          echo "CSS_SELECTOR=${{ github.event.inputs.css_selector }}" >> $GITHUB_ENV
          node generate-config.js

      - name: Run Backstop Reference
        run: npx backstop reference

      - name: Run Backstop Test
        run: npx backstop test

      - name: Deploy HTML Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./backstop_data/html_report
